- name: Main
  hosts: localhost
  any_errors_fatal: false
  ignore_errors: true
  tasks:
    - name: Zsh
      ansible.builtin.include_tasks:
        file: ./tasks/zsh.yaml
      tags:
        - zsh
    - name: Rust
      ansible.builtin.include_tasks:
        file: ./tasks/rust.yaml
      tags:
        - rust
    - name: Node
      ansible.builtin.include_tasks:
        file: ./tasks/node.yaml
      tags:
        - node
    - name: Go
      ansible.builtin.include_tasks:
        file: ./tasks/go.yaml
      tags:
        - go
    - name: Npm packages
      ansible.builtin.include_tasks:
        file: ./tasks/npm-packages.yaml
      tags:
        - npm
    - name: Apt packages
      ansible.builtin.include_tasks:
        file: ./tasks/apt-packages.yaml
      tags:
        - packages
    - name: Alacritty
      ansible.builtin.include_tasks:
        file: ./tasks/alacritty.yaml
      when: rust_nightly is succeeded
      tags:
        - alacritty
    - name: Neovim
      ansible.builtin.include_tasks:
        file: ./tasks/neovim.yaml
      tags:
        - neovim
    - name: Git
      ansible.builtin.include_tasks:
        file: ./tasks/git.yaml
      tags:
        - git
    - name: Tmux
      ansible.builtin.include_tasks:
        file: ./tasks/tmux.yaml
      tags:
        - tmux
    - name: Dotfiles
      ansible.builtin.include_tasks:
        file: ./tasks/dotfiles.yaml
      tags:
        - dotfiles
