- name: Clone alacritty git repo
  ansible.builtin.git:
    repo: "https://github.com/alacritty/alacritty.git"
    dest: "~/alacritty"
    update: true
    version: "master"
  tags:
    - alacritty
- name: Install packages for alacritty
  become: true
  ansible.builtin.apt:
    name:
      - "cmake"
      - "pkg-config"
      - "libfreetype6-dev"
      - "libfontconfig1-dev"
      - "libxcb-xfixes0-dev"
      - "libxkbcommon-dev"
      - "python3"
  tags:
    - alacritty
- name: Build alacritty from source
  ansible.builtin.command:
    cmd: zsh -c "cargo build --release"
    chdir: ~/alacritty
  changed_when: true
  tags:
    - alacritty
- name: Install alacritty terminfo
  become: true
  ansible.builtin.command:
    cmd: tic -xe alacritty,alacritty-direct /home/dog4ik/alacritty/extra/alacritty.info
  changed_when: true
  tags:
    - alacritty
