- name: Install packages(productivity)
  become: true
  ansible.builtin.apt:
    name:
      - "tmux"
      - "fzf"
      - "xclip"
      - "ripgrep"
  tags:
    - packages
    - productivity
- name: Install system packages
  become: true
  ansible.builtin.apt:
    name:
      - "unzip"
      - "build-essential"
      - "libtool"
      - "ffmpeg"
  tags:
    - packages
    - productivity
- name: Install system packages 2
  become: true
  ansible.builtin.apt:
    name:
      - "i3"
      - "python3-pip"
      - "pavucontrol"
      - "picom"
      - "light"
      - "feh"
  tags:
    - packages
    - productivity
