- name: Curl Go archive
  ansible.builtin.uri:
    url: "https://go.dev/dl/go1.21.0.linux-amd64.tar.gz"
    dest: "{{ lookup('env', 'HOME') }}/go-install.tar.gz"
  register: go_zip
  tags:
    - go
- name: Unarchive go
  become: true
  ansible.builtin.unarchive:
    dest: /usr/local
    src: "{{ lookup('env', 'HOME') }}/go-install.tar.gz"
  when: go_zip is succeeded
  changed_when: true
  tags:
    - go
