- name: Setup ppa
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:neovim-ppa/unstable
    state: present
  tags:
    - neovim
- name: Install nvim
  become: true
  ansible.builtin.apt:
    name:
      - neovim
  tags:
    - neovim
