- name: Install fnm
  community.general.cargo:
    name: fnm
    executable: ~/.cargo/bin/cargo
  register: fnm_installed
  tags:
    - node
- name: Install latest node
  ansible.builtin.shell:
    cmd:
      set -o pipefail > /dev/null && eval "$(~/.cargo/bin/fnm env --use-on-cd)" &&
      ~/.cargo/bin/fnm use --install-if-missing $(~/.cargo/bin/fnm ls-remote | tail -n 1)
    executable: /bin/bash
  register: node_path
  when: fnm_installed is succeeded
  changed_when: true
  tags:
    - node
