- name: Install ts
  async: 120
  poll: 0
  ansible.builtin.npm:
    name: typescript
    global: true
  environment:
    PATH: "{{ node_path.stdout }}"
  tags:
    - install
    - node
- name: Install ncu
  async: 120
  poll: 0
  ansible.builtin.npm:
    name: npm-check-updates
    global: true
  environment:
    PATH: "{{ node_path.stdout }}"
  tags:
    - install
    - node
- name: Install tldr
  async: 120
  poll: 0
  ansible.builtin.npm:
    name: tldr
    global: true
  environment:
    PATH: "{{ node_path.stdout }}"
  tags:
    - install
    - node
- name: Install ts-node
  async: 120
  poll: 0
  ansible.builtin.npm:
    name: ts-node
    global: true
  environment:
    PATH: "{{ node_path.stdout }}"
  tags:
    - install
    - node
